### ISSUE TITLE
OTC DNS validation fails because provider tries to create the same TXT record multiple times

### ISSUE THREAD

**Issue by slauger** [vancluever/terraform-provider-acme#278] opened 2023-02-06 09:57 UTC
When using the OTC DNS validation it is currently not possible to enroll a certificate with a subdomain and a wildcard entry for this subdomain in the SAN in combination (e.g. a cert with CN `foo.example.com` and SAN `[*.foo.example.com]`).

This already worked earlier before. At a certain point our setup stopped working w/o chaning our code. I think it was when we upgraded the terraform-acme-provider. Currently we are using v2.12.0. Unfortunately, I can't say with which version the problem occurred.

It seems that the provider tries to create two TXT records with the same name, which is not allowed in the OTC. For example, creating two records like this will result in an API error in the OTC ("This record set name already exists").

```
_acme-challenge.foo.example.com
```
If we deploy a seperate cert for `*.foo.example.com` or `foo.example.com` everything works fine.

Let me know if this is a issue in the lego stack.

```
acme_certificate.certificate["foo.example.com"]: Destroying... [id=b05a4291-0822-4b1a-ddd1-4bee1515c981]
acme_certificate.certificate["foo.example.com"]: Destruction complete after 0s
acme_certificate.certificate["foo.example.com"]: Creating...
acme_certificate.certificate["foo.example.com"]: Still creating... [10s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [20s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [30s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [40s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [50s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [1m0s elapsed]
acme_certificate.certificate["foo.example.com"]: Still creating... [1m10s elapsed]
╷
│ Error: error creating certificate: error: one or more domains had a problem:
│ [*.foo.example.com] [*.foo.example.com] acme: error presenting token: 2 errors occurred:
│ 	* otc: OTC API request https://dns.eu-de.otc.t-systems.com/v2/zones/123141..c017729a86f293abc/recordsets failed with HTTP status code 400
│ 	* error encountered while presenting token for DNS challenge: otc: OTC API request https://dns.eu-de.otc.t-systems.com/v2/zones/123141..c017729a86f293abc/recordsets failed with HTTP status code 400
│ 
│ 
│ 
│ 
│   with acme_certificate.certificate["foo.example.com"],
│   on main.tf line 19, in resource "acme_certificate" "certificate":
│   19: resource "acme_certificate" "certificate" {
│

**Comment by vancluever** [comment] 2023-02-06 23:37
@slauger It should be acceptable to create multiple TXT records, but of course the API could differ - the API here seems to indicate that they use a record set pattern similar to something like AWS Route 53 and hence the record set would need to be modified in-place by appending the new record to the existing record set. Looking through the code, I don't really see that happening in [`Present`](https://github.com/go-acme/lego/blob/e76a104315ca5709367b60723335b6ae35397398/providers/dns/otc/otc.go#L123-L157) for the OTC provider. ([Compare that to Route 53](https://github.com/go-acme/lego/blob/e76a104315ca5709367b60723335b6ae35397398/providers/dns/route53/route53.go#L140-L179).)

Only thing I can really think of is that OTC may have changed their API recently so that it it's more strict about how it handles TXT record modifications.

This for sure might be a lego "issue" in that maybe a review of OTC's API and the existing provider code needs to be done and any updates made if need be, but likely not a bug in the core DNS01 challenge process.

**Comment by slauger** [comment] 2023-02-10 08:50
Thank you for the input. First i will try to create a support ticket in the OTC. We'll see what they say. Maybe they changed the API recently.

Currently you cannot configure something like this in a hosted domain in the OTC and i think this is a general error in the OTC API.

```
-bash$ dig txt txt.example.cloud @1.1.1.1 +short
"good morning"
"hello there"
```

So there is there a way to tell the provider to do the validation step by step? Or maybe avoid the creation of the same record?

**Comment by vancluever** [comment] 2023-02-10 17:14
@slauger yeah no unfortunately, this is purely a lego/DNS provider thing. If the API has changed, then the provider needs to be updated.

**Comment by vancluever** [comment] 2023-02-18 17:10
@slauger closing this out now as it seems to be an issue unrelated to the provider itself.

**Closed by vancluever** 2023-02-18 17:10 UTC
