### ISSUE TITLE
cloudflare: failed to find zone subdomain.example.com.: Zone could not be found

### ISSUE THREAD

**Issue by rfranks-securenet** [vancluever/terraform-provider-acme#139] opened 2021-02-03 13:59 UTC
When trying to issue a cert against a subdomain, using CloudFlare as a DNS provider, it is failing on the basis that Cloudflare can't find the subdomain zone.

Cloudflare does not permit creation of subdomains, only top level ones. In this case, the method for issuing the certificate is by creating a TXT record under the root domain (example.com) that has the name "_acme-challenge.test.subdomain" rather than trying to create within the subdomain zone.

**Comment by vancluever** [comment] 2021-02-09 18:50
Hey @rfranks-securenet, can you try and reproduce your issue with lego's own CLI tool, and if so, submit an issue with them in regards to the CloudFlare DNS provider. More than likely, this is an issue that would need to be fixed in the DNS provider itself, since it seems like it's selecting the incorrect zone for creating DNS records.

Thanks!

**Closed by vancluever** 2021-02-09 18:50 UTC
