### ISSUE TITLE
ACME v2

### ISSUE THREAD

**Issue by adamlc** [vancluever/terraform-provider-acme#26] opened 2018-01-05 08:09 UTC
The ACME v2 protocol now has a staging server. It would be awesome if we could start looking at how this might affect this plugin. The main benefit of v2 is the ability to issue wildcards :)

**Comment by vancluever** [comment] 2018-01-06 23:31
Hey @adamlc, since we depend on https://github.com/xenolf/lego, this hinges on when they end up putting in the support themselves. Looks like they have something in for this, and they are tracking in in xenolf/lego#457.

Once it's in we can look at what's needed to get the TF provider up to snuff.

**Comment by ryanohoro** [comment] 2018-03-13 19:50
API v2 is officially live and lego seems to be aware

https://github.com/xenolf/lego/issues/457

**Comment by vancluever** [comment] 2018-03-13 20:04
Hey @ryanohoro, indeed I've been following that issue and will be vendoring and adopting the changes as soon as they are available upstream!

**Comment by adamlc** [comment] 2018-03-22 08:19
Looks like Lego has done some work in the acmev2 branch :)

**Comment by vancluever** [comment] 2018-04-05 15:26
Hey all, just an update on this because I know there's been some radio silence. I have been watching the lego issue every couple of days to check in on the progress on their end. Once this is actually a thing in master we will be merging it here. I'm hoping to hold off on a 0.6 release until then.

If this is going to take a long time on their end I may also do another bugfix release addressing the other issues in the repository in the meantime, but I've been holding off so I can just do it all in one update batch.

Thanks!

**Comment by t5unamie** [comment] 2018-04-17 14:18
Does anyone know when support for this will be added?

**Comment by vancluever** [comment] 2018-04-17 14:44
@t5unamie as mentioned, I am waiting for the v2 development to conclude in lego and it to be merged to master. The issue is xenolf/lego#457, but please don't inquire about progress over there (not saying that you will, I just want to make sure @xenolf is not bogged down with empty requests or made to feel unduly responsible for the maintenance of a dependent tool).

You can also track https://github.com/xenolf/lego/commits/acmev2 - looks like @xenolf was doing some work today too, so there is progress being made.

Thanks!

**Comment by adamlc** [comment] 2018-05-31 07:30
@vancluever as I'm sure you've probably seen ACME v2 support has been merged to master in lego 👍

**Comment by vancluever** [comment] 2018-05-31 19:19
@adamlc I did check yesterday! :tada: 

Keep an eye out - I will be clearing out the issue log soon and then will be working on the changes necessary to get v2 in.

**Comment by vancluever** [comment] 2018-06-16 18:36
Hey all!

This is very close to being done now - v1.0.0 of the provider is nearly ready and all the tests are passing great with lego 1.x and the ACME v2 endpoints.

There are a couple of more tasks left to do before I release 1.0.0, but as ACME v2 is not one of them, I'm going to close this out now. :slightly_smiling_face: 

I'm hoping to get 1.0.0 complete and released _very_ soon, sometime within the next week. Keep an eye out on the issue tracker and the [1.0.0-dev branch](https://github.com/vancluever/terraform-provider-acme/tree/v1.0.0-dev) for more details!

**Closed by vancluever** 2018-06-16 18:36 UTC
Labels: enhancement

**Comment by vancluever** [comment] 2018-06-17 20:59
Everyone, 1.0.0 is out! Go over to the [release page](https://github.com/vancluever/terraform-provider-acme/releases/tag/v1.0.0) to download and check it out!

**Comment by SamWhited** [comment] 2018-06-17 21:36
Hi, thank you for your work on this plugin!

This comment is to let you know that I've bundled it in the Arch User Repos and updated it to 1.0.0, so if you're running Arch Linux you can install and test easily from the AUR:

https://aur.archlinux.org/packages/terraform-provider-acme-bin/

**Comment by vancluever** [comment] 2018-06-18 14:34
@SamWhited I saw that! That's pretty awesome - thanks for your help making it easier for people to install!

**Comment by adamlc** [comment] 2018-06-18 14:35
@vancluever I migrated about 20 domains over to wildcard's today and the whole process was flawless, many thanks!

**Comment by vancluever** [comment] 2018-06-18 14:49
@adamlc awesome! Glad to see it working at a level of scale! :+1:
