### ISSUE TITLE
Akamai only works with default config section

### ISSUE THREAD

**Issue by danncasey** [vancluever/terraform-provider-acme#215] opened 2021-11-19 03:23 UTC
I setup this module using akamai for dns auth. 
For some reason dns auth only works when the config section is defined as "default".

I can add zones and records using the akamai/akamai provider using the same edgerc and non default config section.  Both modules have the akamai provider setup identically.  The binary from both this module and akamais have the same md5sum.

Simply changing config_section to default and updating my edgerc to match resolves the issue.

**Comment by vancluever** [comment] 2021-11-22 21:56
@danncasey can you paste your config? Fair warning though: it may be lego-related, for which I might not be able to help. You may need to try and reproduce your issues with lego as mentioned [here](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md).

**Comment by vancluever** [comment] 2022-01-18 00:53
Closing this issue due to age. Feel free to put in a another issue if you still need help!

**Closed by vancluever** 2022-01-18 00:53 UTC
