### ISSUE TITLE
[acme 2.0.0] gcloud provider cert renewal time limit exceeded is back

### ISSUE THREAD

**Issue by shmykyta** [vancluever/terraform-provider-acme#141] opened 2021-02-08 18:24 UTC
Used versions: 
```
terraform {
  required_providers {
    acme = {
      source  = "vancluever/acme"
      version = "= 2.0.0"
    tls = {
      source  = "hashicorp/tls"
      version = "= 3.0.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "= 3.53.0"
    }
  }
  required_version = "= 0.14.2"
}
```

Terraform code:
```
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.private_key.private_key_pem
  email_address   = var.email
}

resource "acme_certificate" "certificate" {
  account_key_pem    = acme_registration.reg.account_key_pem
  common_name        = "${var.name}.${var.domain}.com"
  min_days_remaining = 40
  dns_challenge {
    provider = "gcloud"
    config = {
      GCE_POLLING_INTERVAL    = "10"
      GCE_PROPAGATION_TIMEOUT = "180"
      GCE_SERVICE_ACCOUNT     = <account>
      GCE_TTL                 = "60"
      GCE_PROJECT             = var.project_id
    }
  }
}
```

Original error:
```
module.certificates.acme_certificate.certificate: Still modifying... [2m50s elapsed]
module.certificates.acme_certificate.certificate: Still modifying... [3m0s elapsed]
module.certificates.acme_certificate.certificate: Still modifying... [3m10s elapsed]

Error: error: one or more domains had a problem:
[xxx.xxx.xxx.com] time limit exceeded: last error: NS ns-cloud-e3.googledomains.com. did not return the expected TXT record [fqdn: _acme-challenge.xxx.xxx.xxx.com., value: <VALUE>]: 
```

Error in debug mode:
```
module.certificates.acme_certificate.certificate: Still modifying... [3m10s elapsed]
2021-02-05T18:08:47.546+0200 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/05 18:08:47 [DEBUG] lego: [xxx.xxx.xxx.com] acme: Waiting for DNS record propagation.: timestamp=2021-02-05T18:08:47.546+0200
module.certificates.acme_certificate.certificate: Still modifying... [3m20s elapsed]
2021-02-05T18:08:57.547+0200 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/05 18:08:57 [DEBUG] lego: [xxx.xxx.xxx.com] acme: Cleaning DNS-01 challenge: timestamp=2021-02-05T18:08:57.547+0200
2021-02-05T18:09:01.175+0200 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/05 18:09:01 [DEBUG] lego: retry due to: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/authz-v3/10629620581 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: "0104c-M2KAX5z1Ngb0TaclqklBFNpczaeaEgG3d1zyuuuSI", url:: timestamp=2021-02-05T18:09:01.175+0200
2021-02-05T18:09:01.596+0200 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/05 18:09:01 [DEBUG] lego: Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/10629620581: timestamp=2021-02-05T18:09:01.596+0200
2021/02/05 18:09:01 [DEBUG] module.certificates.acme_certificate.certificate: apply errored, but we're indicating that via the Error pointer rather than returning it: error: one or more domains had a problem:
[xxx.xxx.xxx.com] time limit exceeded: last error: NS ns-cloud-e3.googledomains.com. did not return the expected TXT record [fqdn: _acme-challenge. xxx.xxx.xxx.com., value: VALUE]: 
```

record successfully created:
```
dig _acme-challenge.xxx.xxx.xxx.com 

; <<>> DiG 9.10.6 <<>> _acme-challenge.xxx.xxx.xxx.com 
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12876
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_acme-challenge.xxx.xxx.xxx.com. IN A

;; AUTHORITY SECTION:
xxx.xxx.com.		300	IN	SOA	ns-cloud-e1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300

;; Query time: 809 msec
;; SERVER: 100.95.0.251#53(100.95.0.251)
;; WHEN: Mon Feb 08 19:49:02 EET 2021
;; MSG SIZE  rcvd: 155

```

I research the issues like these one https://github.com/vancluever/terraform-provider-acme/issues/87 and https://github.com/vancluever/terraform-provider-acme/issues/65 and tried to play with timeout and `pre_check_delay` option, but no luck, even in 20-30 times run the terraform I have same result with this error..
Before it's worked like a charm, seems it's a bug in 2.0.0 version?

**Comment by romankor** [comment] 2021-02-09 03:59
I would like to add some findings to @shmykyta , we are working on the same issue. 

That happens exclusively when trying to generate a certificate for a subdomain in Google DNS

I did provide custom `recursive_nameservers`

```terraform
data "google_dns_managed_zone" "zone" {
  name = "${var.namespace}-xxx-com"
}

resource "acme_certificate" "global_xxx_certificate" {
  account_key_pem    = acme_registration.reg.account_key_pem
  certificate_request_pem = tls_cert_request.certificate.cert_request_pem
  min_days_remaining = 30
  recursive_nameservers = data.google_dns_managed_zone.zone.name_servers

  dns_challenge {
    provider = "gcloud"
    config = {
      GCE_POLLING_INTERVAL    = "10"
      GCE_PROPAGATION_TIMEOUT = "180"
      GCE_TTL                 = "60"
      GCE_SERVICE_ACCOUNT     = base64decode(data.vault_generic_secret.vault_sa_keys.data["dns_admin"])
      GCE_PROJECT             = var.project_id
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

So we are trying to generate a certificate for a subdomain with namerservers : 

```terraform 
  # module.certificates.acme_certificate.global_xxx_certificate will be created
  + resource "acme_certificate" "global_xxx_certificate" {
      + account_key_pem              = (sensitive value)
      + certificate_domain           = (known after apply)
      + certificate_p12              = (sensitive value)
      + certificate_pem              = (known after apply)
      + certificate_request_pem      = <<-EOT
            -----BEGIN CERTIFICATE REQUEST-----
xxxx
            -----END CERTIFICATE REQUEST-----
        EOT
      + certificate_url              = (known after apply)
      + disable_complete_propagation = false
      + id                           = (known after apply)
      + issuer_pem                   = (known after apply)
      + key_type                     = "2048"
      + min_days_remaining           = 30
      + must_staple                  = false
      + pre_check_delay              = 0
      + private_key_pem              = (sensitive value)
      + recursive_nameservers        = [
          + "ns-cloud-a1.googledomains.com.",
          + "ns-cloud-a2.googledomains.com.",
          + "ns-cloud-a3.googledomains.com.",
          + "ns-cloud-a4.googledomains.com.",
        ]

      + dns_challenge {
          + config   = (sensitive value)
          + provider = "gcloud"
        }
    }
```

when resolving i see the acme_challange TXT record being properly created in the subdomain and in the logs i see the proper nameservers : 

```
2021-02-08T19:47:00.095-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:00 [DEBUG] lego: AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/10718652894: timestamp=2021-02-08T19:47:00.094-0800
2021-02-08T19:47:00.095-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:00 [DEBUG] lego:  acme: Could not find solver for: tls-alpn-01: timestamp=2021-02-08T19:47:00.094-0800
2021-02-08T19:47:00.095-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:00 [DEBUG] lego: acme: Could not find solver for: http-01: timestamp=2021-02-08T19:47:00.095-0800
2021-02-08T19:47:00.095-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:00 [DEBUG] lego:  acme: use dns-01 solver: timestamp=2021-02-08T19:47:00.095-0800
2021-02-08T19:47:00.095-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:00 [DEBUG] lego:  acme: Preparing to solve DNS-01: timestamp=2021-02-08T19:47:00.095-0800
2021-02-08T19:47:01.473-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:01 [DEBUG] lego: Wait for apply change [timeout: 30s, interval: 3s]: timestamp=2021-02-08T19:47:01.473-0800
2021-02-08T19:47:01.598-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:01 [DEBUG] lego: acme: Trying to solve DNS-01: timestamp=2021-02-08T19:47:01.598-0800
2021-02-08T19:47:01.598-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:01 [DEBUG] lego:  acme: Checking DNS record propagation using [ns-cloud-a1.googledomains.com.:53 ns-cloud-a2.googledomains.com.:53 ns-cloud-a3.googledomains.com.:53 ns-cloud-a4.googledomains.com.:53]: timestamp=2021-02-08T19:47:01.598-0800
module.certificates.acme_certificate.global_relay_certificate: Still creating... [10s elapsed]
2021-02-08T19:47:11.601-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:47:11 [DEBUG] lego: Wait for propagation [timeout: 3m0s, interval: 10s]: timestamp=2021-02-08T19:47:11.601-0800



module.certificates.acme_certificate.global_relay_certificate: Still creating... [3m10s elapsed]
2021-02-08T19:50:17.006-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:50:17 [DEBUG] lego: acme: Cleaning DNS-01 challenge: timestamp=2021-02-08T19:50:17.005-0800
2021-02-08T19:50:17.813-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:50:17 [DEBUG] lego: retry due to: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/authz-v3/10718652894 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: "0103BcV9tG-HBA7W1pCPOefEBQmsoxEyuGnsmi463u1UQd4", url:: timestamp=2021-02-08T19:50:17.813-0800
2021-02-08T19:50:18.128-0800 [INFO]  plugin.terraform-provider-acme_v2.0.0: 2021/02/08 19:50:18 [DEBUG] lego: Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/10718652894: timestamp=2021-02-08T19:50:18.128-0800
2021/02/08 19:50:18 [DEBUG] module.certificates.acme_certificate.global_relay_certificate: apply errored, but we're indicating that via the Error pointer rather than returning it: error creating certificate: error: one or more domains had a problem:
time limit exceeded: last error: NS ns-cloud-e4.googledomains.com. did not return the expected TXT record [fqdn: _acme-challenge.relays.xxx.xxx.com., value: _W2_ibyH2OdqkIuCU1hgETQc54zXuHnV1Yy4SEuR3dQ]:

Error: error creating certificate: error: one or more domains had a problem:
 time limit exceeded: last error: NS ns-cloud-e4.googledomains.com. did not return the expected TXT record [fqdn: _acme-challenge.relays.xxx.xxx.com., value: _W2_ibyH2OdqkIuCU1hgETQc54zXuHnV1Yy4SEuR3dQ]:

```

The error message in the end points to the name servers of the main domain and not to the subdomain , which i suspect is the reason for the error

**Comment by vancluever** [comment] 2021-02-09 18:57
Hey @shmykyta, I can't really think of anything introduced in the provider itself that would have caused this issue. My best recommendation is to attempt to reproduce this with the [lego CLI tool](https://go-acme.github.io/lego/installation/) and see if you can re-produce it consistently.

Unfortunately the Google Cloud provider has historically been flaky, and there isn't much I can do here, other than recommend you use a different DNS provider if possible. Sorry for not being able to help further!

**Closed by vancluever** 2021-02-09 18:57 UTC

**Comment by shmykyta** [comment] 2021-02-09 19:35
@vancluever thanks for the answer
seems we found workaround. It's tried to propagate to another NS and of course can't find the record..
```
data "google_dns_managed_zone" "zone" {
   name = var.my_zone
 }
 
 resource "acme_certificate" "certificate" {
   ...
   recursive_nameservers = data.google_dns_managed_zone.zone.name_servers
   pre_check_delay = 30
   ...
   dns_challenge {
     provider = "gcloud"
     config = {
     ...
     }
 }
```

in configuration like this everything worked, but propagation takes like 20 mins

**Comment by vancluever** [comment] 2021-02-09 23:32
@shmykyta the DNS provider docs are automated now, and we haven't needed local annotations yet so I haven't rolled that feature into the generator. I'd also prefer to keep workarounds like this in the issue tracker just in case the settings have some unintended consequences or ultimately are no longer needed.

I've added some direction recently to try and ensure people use the issue tracker as a bit of a knowledge base, so people should hopefully come across this if they have the same issue. 🙂
