### ISSUE TITLE
Failed to install provider

### ISSUE THREAD

**Issue by mgismaco** [vancluever/terraform-provider-acme#382] opened 2024-02-13 15:50 UTC
│ Error: Failed to install provider
│
│ Error while installing vancluever/acme v2.20.0: error checking signature: openpgp: key expired

**Comment by vancluever** [comment] 2024-02-13 17:23
@mgismaco I'm looking into this right now. In the meantime can you tell me how you are installing the provider and how you have it in configured in Terraform? I'm unable to reproduce the verification error (although I have confirmed the key is expired):

```
- Installing vancluever/acme v2.20.0...
- Installed vancluever/acme v2.20.0 (self-signed, key ID F282F2CFA56C3D69)
```

**Comment by vancluever** [comment] 2024-02-13 18:39
The key has been updated and there should be a release in the next couple of hours. Closing this. For verification, the new key ID is `1D9DFB214E18E085`.

**Closed by vancluever** 2024-02-13 18:39 UTC

**Comment by vancluever** [comment] 2024-02-13 19:03
For some reason the TF release process requires an encryption key in the signing key keychain, so I've had to re-issue a new key. The new key is is `974239543C576C78`, and hopefully this one works.

**Comment by vancluever** [comment] 2024-02-13 19:28
Just adding for reference in case I need to do it again (although the key has been set now to never expire): This is due to an old version of https://github.com/crazy-max/ghaction-import-gpg which was resolved close to two and a half years ago now. The workflow currently uses an old fork but it looks like we can [safely move to upstream](https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410).

Not planning on doing it anytime soon but this makes it easy to know how to make the transition when I plan on doing so.
