### ISSUE TITLE
Race condition in assuming IAM role for route53 provider

### ISSUE THREAD

**Issue by irl** [vancluever/terraform-provider-acme#371] opened 2024-01-15 10:36 UTC
When running 7 certificate renewals in parallel, all with the route53 provider and each with their own IAM role for the job, one of the renewals failed with a permission denied error. The error showed that the wrong role had been assumed for that resource, and it had assumed a role from a different resource in another module. This makes me think that parallel executions may be sharing some state and that there's the possibility of credentials leaking between resources.

I don't know if it's the provider that is specifying where the credentials go, or if that's lego. If it is lego then please close the issue and I'll try to reproduce this with the lego CLI.

A workaround that could perhaps be implemented in the provider would be to not allow parallel execution when the route53 provider is being used with specified credentials.

A second run of the Terraform created the remaining certificate without issue.

**Comment by vancluever** [comment] 2024-01-16 00:26
@irl credential races should have been fixed in https://github.com/vancluever/terraform-provider-acme/pull/276 (see https://github.com/vancluever/terraform-provider-acme/issues/235). Pretty much the same issue you're mentioning, although there's possibly some other things that could be affecting things on AWS, such as local configuration files, although you did mention running again fixed the issue, so I'm not too sure there.

Additionally there should not be any more state shared between resource instances and each one should be launching its own sub-process to set environment in. There should be no instance caching or anything like that either (obviously that's what we're trying to avoid). I quickly double-checked the startup routines in [go-plugin](https://github.com/hashicorp/go-plugin) (which drives this whole process) just to be sure.

I'll look into it a bit more over the week and see if I can find anything. I don't think this is a lego issue, but I also can't think of where we'd be leaking configuration between resource instances anymore, so barring any on-disk credential chain configuration that would be causing the issue, I can't think of anything else that would be the cause right now.

**Comment by vancluever** [comment] 2024-06-06 18:59
@irl I don't think I ended up coming up with anything, and barring any further info here, I don't think there's anything we can do here. If you ended up getting any further info on this that'd be useful in tracking down this issue, feel free to reply!

**Closed by vancluever** 2024-06-06 18:59 UTC
